name: Update Social Videos

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 */3 * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: echo "INSTAGRAM_ACCESS_TOKEN is set: ${{ secrets.INSTAGRAM_ACCESS_TOKEN != '' }}"
      - run: npm run update-social
        env:
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
      - run: |
          git config user.name wotanCode
          git config user.email 72775296+wotanCode@users.noreply.github.com
          git add src/content/InstagramPost.md
          git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update Instagram posts"
          git push origin main
