name: Update Social Videos

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 1,22 * *"

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      
      - run: npm install
      
      - name: Check Token Length
        run: |
          echo "Token length: ${#INSTAGRAM_ACCESS_TOKEN}"
        env:
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
      
      - name: Update Social Posts
        run: npm run update-social
        env:
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
      
      - name: Commit and Push Changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "72775296+${{ github.actor }}@users.noreply.github.com"
          git add src/content/InstagramPost.md
          git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update Instagram posts [skip ci]"
          git pull --rebase origin main
          git push origin HEAD:main
